---
title: "Index"
author: "Borden"
date: "April 6, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

Agenda: 
1. Reviewed Github and file structure
2. Going through a series of R demos (vignettes)
  * Diagrammaer: draw your own workflows
  * Data simulation: draw your own workflows
    * graph the results
  * Making a map of the United States
  * Grab Andrew's Data set

```{r loading libraries}
install.packages("ggplot2")
library(ggplot2)
install.packages("dplyr")
library(dplyr)
```

```{r}
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("tidyr", "maps", "mapdata", "DiagrammeR", "ggplot2","dplyr","data.table")
ipak(packages)
```

```{r}
install.packages("DiagrammeR")
library(DiagrammeR)
```





```{r Diagrammer demo}
mermaid("
graph TD
A[Make dataset] --> B[Run statistics]
        ")
```
```{r}
mermaid("
graph TD
        A[Make dataset sampling the same distr] --> B[Run statistics]
C[Make dataset sampling diff distr] --> B
B --> D[Finish]
                ")
```
```{r}
Treatment<-c(rep("Control",50),rep("Intervention",50));Treatment

#generate a set of normally distributed values
rand.num1<-rnorm(n=1000,mean=50,sd=10)

Measurements<-sample(rand.num1,length(Treatment))

dat<-data.frame(Treatment,Measurements)
glimpse(dat)

head(dat)
tail(dat)

#lets query the data in diff ways
dat%>%
  group_by(Treatment)%>%
  summarise(sample_size=length(Measurements))
  

mod1<-aov(Measurements~Treatment, data = dat)
summary(mod1)

rand.num2<-(rnorm(1000,mean=100,sd=10))
head(rand.num2)
head(dat)

dat$Measurements2<-c(sample(rand.num1,50),sample(rand.num2,50))

head(dat)
glimpse(dat)

#lets construct anova model
mod2<-aov(Measurements2~Treatment,data=dat)
summary(mod2)

#lets plot the distributions
ggplot(dat,aes(x=Measurements,fill=Treatment))+geom_histogram(position="identity",alpha=.2)

ggplot(dat,aes(x=Measurements,fill=Treatment))+geom_density(position="identity",alpha=.2)

ggplot(dat,aes(x=Measurements2,fill=Treatment))+geom_density(position="identity",alpha=.2)

fwrite(dat,"2018-04-06_data.csv") #write out the dataset into a csv file in the folder.
```
### Making maps

```{r}
map()
map("usa")
map()
points(x=80,y=5,cex=4,pch=20,col="red")



```



